/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jun 23 22:00:19 CEST 2005 by MyEclipse Hibernate Tool.
 */
package com.schedule.hibernate;

import java.io.Serializable;

/**
 * A class that represents a row in the Preferences table. 
 * You can customize the behavior of this class by editing the class, {@link Preferences()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractPreferences 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer uid;

    /**
     * Simple constructor of AbstractPreferences instances.
     */
    public AbstractPreferences()
    {
    }

    /**
     * Constructor of AbstractPreferences instances given a simple primary key.
     * @param uid
     */
    public AbstractPreferences(java.lang.Integer uid)
    {
        this.setUid(uid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getUid()
    {
        return uid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param uid
     */
    public void setUid(java.lang.Integer uid)
    {
        this.hashValue = 0;
        this.uid = uid;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Preferences))
            return false;
        Preferences that = (Preferences) rhs;
        if (this.getUid() != null && that.getUid() != null)
        {
            if (! this.getUid().equals(that.getUid()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int uidValue = this.getUid() == null ? 0 : this.getUid().hashCode();
            result = result * 37 + uidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
